server:
  port: 8081

kafka:
  topic:
    consume: "headhunterVacancyStorage"
    produce: "headhunterVacancyNotification"

spring:
  kafka:
    bootstrap-servers: "localhost:29092"
    consumer:
      client-id: "storage-vacancy-consumer"
      group-id: "storage-vacancy-group"
      auto-offset-reset: earliest

  data:
    mongodb:
      uri: mongodb://localhost:27017/Vacancy