server:
  port: 8083

kafka:
  topic-consume: "headhunterVacancyNotification"

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/customers
    username: customer
    password: customer

  jpa:
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: "localhost:29092"
    consumer:
      client-id: "notification-vacancy-consumer"
      group-id: "notification-vacancy-group"
      auto-offset-reset: earliest